import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'ar' | 'en';

interface LanguageContextType {
  language: Language;
  toggleLanguage: () => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  ar: {
    nav_home: 'الرئيسية',
    nav_about: 'عن الشركة',
    nav_services: 'خدماتنا',
    nav_industries: 'القطاعات',
    nav_projects: 'المشاريع',
    nav_clients: 'العملاء والشركاء',
    nav_contact: 'اتصل بنا',

    hero_title: 'المجد العربي الحديث للمقاولات العامة والتصنيع الصناعي',
    hero_subtitle: 'رائدون في تقديم حلول الإنشاءات والتصنيع عالية الجودة في المملكة العربية السعودية',
    hero_cta_services: 'اكتشف خدماتنا',
    hero_cta_contact: 'تواصل معنا',

    about_title: 'عن الشركة',
    about_subtitle: 'تأسست شركة المجد لسد الفجوة في السوق السعودي عبر تقديم منتجات وخدمات عالية الجودة.',
    about_description: 'نحن شركة رائدة في مجال المقاولات العامة والتصنيع الصناعي، نقدم حلولاً متكاملة للمشاريع الصناعية والتجارية والسكنية في المملكة العربية السعودية.',
    mission_title: 'رسالتنا',
    mission_text: 'تقديم خدمات عالية الجودة في تصنيع الفولاذ والنفط وأنابيب المعالجة وإمداد القوى العاملة، مع فريق مخصص وموجه نحو الخدمة، وبناء شراكات طويلة الأمد.',
    vision_title: 'رؤيتنا',
    vision_text: 'أن نكون المركز الرئيسي للمشاريع والمنتجات المتماشية مع الأهداف المؤسسية، وإقامة شراكات مع قادة الصناعة، ودمج التقنيات الجديدة، وتقديم فرص استثمارية قوية.',
    chairman_message: 'تأسست شركة المجد لتقديم منتجات وخدمات بمستوى معايير دولية تُنفّذ محليًا بجودة عالية وتكلفة تنافسية. نركز على تقديم قيمة حقيقية، ورفع إنتاجية عملائنا، والمساهمة في نمو المملكة.',
    chairman_name: 'محمد عيد - الرئيس',
    quality_policy_title: 'سياسة الجودة',
    quality_policy_text: 'العمل الجماعي المثالي، أفضل المواد الخام، تطبيق أعلى معايير السلامة، المسؤولية البيئية، والمعالجة الفورية لشكاوى العملاء.',
    safety_policy_title: 'سياسة السلامة',
    safety_policy_text: 'التدريب الشامل، أنظمة العمل الآمنة، القيادة الدفاعية، المراقبة المستمرة، والالتزام بالمتطلبات والأنظمة القانونية.',

    services_title: 'خدماتنا',
    services_subtitle: 'نقدم مجموعة شاملة من الخدمات لتلبية جميع احتياجاتك',
    service1_title: 'الأعمال المدنية',
    service1_desc: 'البناء والصيانة والتعديل والتجديد للمباني الصناعية والتجارية والسكنية',
    service2_title: 'الأعمال الميكانيكية',
    service2_desc: 'أنابيب النفط والغاز وأعمال التشغيل وخزانات التخزين وأنظمة مكافحة الحريق',
    service3_title: 'الهياكل الفولاذية والتصنيع',
    service3_desc: 'تصنيع الفولاذ والستانلس ستيل واللحام والسفع الرملي وإعادة التكييف',
    service4_title: 'الألومنيوم والزجاج',
    service4_desc: 'أبواب ونوافذ الألومنيوم عالية المعايير والحوائط الستائرية والكسوة',
    service5_title: 'أنظمة مكافحة الحريق',
    service5_desc: 'طفايات الحريق والإنذارات والرشاشات وأنظمة الإطفاء',
    service6_title: 'الكهرباء والأجهزة',
    service6_desc: 'الكهرباء ذات الجهد المنخفض/المتوسط/العالي ووضع الكابلات والاختبار',
    service7_title: 'أعمال التشطيبات الداخلية',
    service7_desc: 'حلول شاملة للمكاتب والإسكان وصالات العرض والمطاعم',

    industries_title: 'القطاعات',
    industries_subtitle: 'نخدم مجموعة واسعة من القطاعات الصناعية',
    industry1_title: 'النفط والغاز',
    industry1_desc: 'تركيب خطوط الأنابيب، خزانات التخزين، والمنشآت البتروكيميائية',
    industry2_title: 'المباني التجارية',
    industry2_desc: 'مجمعات المكاتب، مراكز التسوق، والمشاريع متعددة الاستخدام',
    industry3_title: 'المياه والمرافق',
    industry3_desc: 'محطات معالجة المياه، محطات الضخ، وبنية تحتية للمرافق',
    industry4_title: 'الطاقة والكهرباء',
    industry4_desc: 'البنية التحتية الكهربائية، توزيع الطاقة، ومنشآت الطاقة',
    industry5_title: 'السكنية',
    industry5_desc: 'مشاريع الإسكان، الفلل، والمجمعات السكنية',
    industry6_title: 'الصناعات',
    industry6_desc: 'المصانع، المستودعات، والمجمعات الصناعية',

    projects_title: 'المشاريع',
    projects_ongoing: 'المشاريع الجارية ٢٠٢٤',
    projects_completed: 'المشاريع المنجزة (آخر ١٠ سنوات)',
    project1_name: 'دلتا للتعاون',
    project1_type: 'منطقة صناعية',
    project2_name: 'مبنى الإدارة أرامكو',
    project2_type: 'هيكل فولاذي',
    project3_name: 'مستشفى تداوي العام',
    project3_type: 'منشأة طبية',
    project4_name: 'سينما موافي الظهران',
    project4_type: 'مجمع ترفيهي',
    project5_name: 'خط مكافحة الحرائق أرامكو',
    project5_location: 'القطيف',
    project6_name: 'حرم جامعة الملك عبدالعزيز',
    project7_name: 'توسعة مصنع الأسمنت السعودي',

    clients_title: 'العملاء والشركاء',
    clients_subtitle: 'نفخر بالعمل مع أفضل الشركات في المملكة',
    client1: 'أرامكو السعودية',
    client2: 'شركة اليمامة',
    client3: 'الأسمنت السعودية',
    client4: 'جامعة الملك عبدالعزيز',
    client5: 'مجموعة بن لادن',
    client6: 'الفطيم (فولفو)',

    contact_title: 'تواصل معنا',
    contact_subtitle: 'نحن هنا لمساعدتك في مشروعك القادم',
    contact_address: 'العنوان',
    contact_phone: 'الهاتف',
    contact_email: 'البريد الإلكتروني',
    contact_whatsapp: 'واتساب',
    address_line1: 'الخبر – ٣٤٤٤٨ – العليا',
    address_line2: 'الخبر، المملكة العربية السعودية',

    footer_about_title: 'عن الشركة',
    footer_about_text: 'شركة رائدة في مجال المقاولات العامة والتصنيع الصناعي في المملكة العربية السعودية',
    footer_contact_title: 'معلومات التواصل',
    footer_links_title: 'روابط سريعة',
    footer_services_title: 'الخدمات',
    footer_cr: 'س.ت: ٧٠٥٠٦٠٧٩٥٦',
    footer_copyright: '© {year} المجد العربي الحديث جميع الحقوق محفوظة',
    footer_website: 'الموقع الإلكتروني',

    login: 'دخول',
    logout: 'خروج',
    profile: 'الملف',
    my_profile: 'ملفي الشخصي',
    admin_panel: 'لوحة الإدارة',
    username: 'اسم المستخدم',
    email_address: 'البريد الإلكتروني',
    password: 'كلمة المرور',
    sign_in: 'تسجيل الدخول',
    signing_in: 'جاري تسجيل الدخول...',
    test_account: 'حساب تجريبي',
    phone_number: 'رقم الهاتف',
    position: 'المنصب',
    department: 'القسم',
    member_since: 'عضو منذ',
    close: 'إغلاق',
    not_provided: 'غير متوفر',
    not_specified: 'غير محدد',
    enter_password: 'أدخل كلمة المرور',
    full_name: 'الاسم الكامل',
    user: 'مستخدم',
    no_position: 'لا يوجد منصب محدد',

    toggle_language: 'تبديل اللغة',
    login_failed: 'تعذر تسجيل الدخول',

    public_profile_title: 'الملف العام',
    public_profile_back_home: 'العودة للموقع',
    public_profile_not_found: 'لا يوجد ملف عام لهذا المستخدم حالياً.',
    public_profile_load_error: 'تعذر تحميل البيانات حالياً.',
    public_profile_whatsapp: 'واتساب',
    public_profile_phone: 'الهاتف',
    public_profile_email: 'البريد الإلكتروني',
    public_profile_share: 'مشاركة الصفحة',
    public_profile_copied: 'تم نسخ الرابط',
    public_profile_copy_failed: 'تعذر نسخ الرابط',
    public_profile_shared: 'تمت المشاركة',
    public_profile_flip_hint: 'اسحب لليمين أو اليسار لعرض رمز QR',
    public_profile_qr_alt: 'رمز QR للملف العام',

    admin_public_profiles_title: 'الملفات العامة',
    admin_new_user: 'مستخدم جديد',
    admin_logout: 'تسجيل الخروج',
    admin_default_user_aria: 'المستخدم الافتراضي',
    admin_edit_user: 'تعديل مستخدم',
    admin_add_user: 'إضافة مستخدم',
    admin_delete: 'حذف',
    admin_field_public_code: 'الكود (4 أرقام)',
    admin_public_code_hint: 'يتكون من 4 أرقام (0001 إلى 9999). الكود 0000 محجوز للمستخدم الافتراضي.',
    admin_public_code_auto: 'يتم توليده تلقائياً عند إضافة مستخدم جديد',
    admin_public_code_required: 'حقل الكود مطلوب.',
    admin_public_code_invalid: 'الكود يجب أن يكون 4 أرقام فقط.',
    admin_public_code_reserved: 'الكود 0000 محجوز للمستخدم الافتراضي.',
    admin_field_name: 'الاسم',
    admin_field_position: 'المسمى الوظيفي',
    admin_field_phone: 'الهاتف',
    admin_field_whatsapp: 'واتساب',
    admin_field_email: 'البريد الإلكتروني',
    admin_field_image: 'رابط صورة المستخدم',
    admin_account_status: 'حالة الحساب',
    admin_status_active: 'نشط',
    admin_status_inactive: 'غير نشط',
    admin_default_user: 'المستخدم الافتراضي',
    admin_save: 'حفظ البيانات',
    admin_save_success: 'تم حفظ البيانات بنجاح',
    admin_load_error: 'تعذر تحميل البيانات',
    admin_refresh_error_after_save: 'تم حفظ البيانات لكن تعذر تحديث القائمة',
    admin_refresh_error_after_delete: 'تم حذف البيانات لكن تعذر تحديث القائمة',
    admin_save_error: 'تعذر حفظ البيانات',
    admin_save_error_with_reason: 'تعذر حفظ البيانات: {message}',
    admin_delete_default_forbidden: 'لا يمكن حذف المستخدم الافتراضي.',
    admin_delete_error: 'فشل حذف البيانات',
    admin_default_user_note: 'هذا هو المستخدم الافتراضي ولا يمكن حذفه أو تعديله من هنا. تعديل بياناته يكون من قاعدة البيانات فقط.',
    admin_qr_code: 'رمز QR',
    admin_qr_alt: 'رمز QR للرابط',
    admin_download_png: 'تحميل PNG',
    admin_download_svg: 'تحميل SVG',
    admin_delete_modal_title: 'هل أنت متأكد من حذف هذا المستخدم؟',
    admin_delete_modal_user: 'المستخدم:',
    admin_delete_modal_warning: 'لا يمكن التراجع عن هذا الإجراء.',
    admin_cancel: 'إلغاء',
    admin_confirm_delete: 'نعم، احذف',
  },
  en: {
    nav_home: 'Home',
    nav_about: 'About',
    nav_services: 'Services',
    nav_industries: 'Industries',
    nav_projects: 'Projects',
    nav_clients: 'Clients & Partners',
    nav_contact: 'Contact',

    hero_title: 'Al-Majd Al-Arabi Al-Hadith for General Contracting & Industrial Fabrication',
    hero_subtitle: 'Leading provider of high-quality construction and fabrication solutions in Saudi Arabia',
    hero_cta_services: 'Discover Our Services',
    hero_cta_contact: 'Contact Us',

    about_title: 'About Us',
    about_subtitle: 'Al‑Majd was established to bridge the gap in the Saudi market by delivering high‑quality products and services.',
    about_description: 'We are a leading company in general contracting and industrial fabrication, providing integrated solutions for industrial, commercial, and residential projects in Saudi Arabia.',
    mission_title: 'Our Mission',
    mission_text: 'Delivering high-quality services in steel fabrication, oil and gas processing pipelines, and workforce supply, with a dedicated service-oriented team, building long-term partnerships.',
    vision_title: 'Our Vision',
    vision_text: 'To be the primary hub for projects and products aligned with institutional goals, establishing partnerships with industry leaders, integrating new technologies, and providing strong investment opportunities.',
    chairman_message: 'Al‑Majd was founded to deliver internationally aligned products and services—executed locally with high quality and competitive cost. We focus on creating real value, improving our clients\' productivity, and contributing to the Kingdom\'s growth.',
    chairman_name: 'Mohammed Eid - Chairman',
    quality_policy_title: 'Quality Policy',
    quality_policy_text: 'Ideal teamwork, best raw materials, applying highest safety standards, environmental responsibility, and prompt handling of customer complaints.',
    safety_policy_title: 'Safety Policy',
    safety_policy_text: 'Comprehensive training, safe work systems, defensive driving, continuous monitoring, and compliance with legal requirements and regulations.',

    services_title: 'Our Services',
    services_subtitle: 'We offer a comprehensive range of services to meet all your needs',
    service1_title: 'Civil Works',
    service1_desc: 'Construction, maintenance, modification, and renovation of industrial, commercial, and residential buildings',
    service2_title: 'Mechanical Works',
    service2_desc: 'Oil and gas piping and commissioning works, storage tanks, and fire fighting systems',
    service3_title: 'Steel Structures & Fabrication',
    service3_desc: 'Steel and stainless steel fabrication, welding, sand blasting, and reconditioning',
    service4_title: 'Aluminum & Glass',
    service4_desc: 'High-standard aluminum doors and windows, curtain walls, and cladding',
    service5_title: 'Fire Fighting Systems',
    service5_desc: 'Fire extinguishers, alarms, sprinklers, and suppression systems',
    service6_title: 'Electrical & Instrumentation',
    service6_desc: 'Low/medium/high voltage electrical, cable laying, and testing',
    service7_title: 'Interior Fit-Out Works',
    service7_desc: 'Comprehensive solutions for offices, housing, showrooms, and restaurants',

    industries_title: 'Industries',
    industries_subtitle: 'We serve a wide range of industrial sectors',
    industry1_title: 'Oil & Gas',
    industry1_desc: 'Pipeline installation, storage tank construction, and petrochemical facilities',
    industry2_title: 'Commercial Developments',
    industry2_desc: 'Office complexes, retail centres, and mixed-use projects',
    industry3_title: 'Water & Utilities',
    industry3_desc: 'Water treatment plants, pumping stations, and utility infrastructure',
    industry4_title: 'Power & Energy',
    industry4_desc: 'Electrical infrastructure, power distribution, and energy facilities',
    industry5_title: 'Residential Communities',
    industry5_desc: 'Housing developments, villas, and residential compounds',
    industry6_title: 'Industrial Facilities',
    industry6_desc: 'Manufacturing plants, warehouses, and industrial complexes',

    projects_title: 'Projects',
    projects_ongoing: 'Ongoing Projects 2024',
    projects_completed: 'Completed Projects (Last 10 Years)',
    project1_name: 'Delta Cooperation Factory',
    project1_type: 'Industrial Zone',
    project2_name: 'Aramco Admin Building',
    project2_type: 'Steel Structure',
    project3_name: 'Tadawi General Hospital',
    project3_type: 'Medical Facility',
    project4_name: 'Mawafi Cinema Dhahran',
    project4_type: 'Entertainment Complex',
    project5_name: 'Aramco Qatif Firefighting Pipeline',
    project5_location: 'Qatif',
    project6_name: 'King Abdulaziz University Campus',
    project7_name: 'Saudi Cement Factory Expansion',

    clients_title: 'Clients & Partners',
    clients_subtitle: 'We are proud to work with the best companies in the Kingdom',
    client1: 'Saudi Aramco',
    client2: 'Al-Yamama',
    client3: 'Saudi Cement',
    client4: 'King Abdulaziz University',
    client5: 'Binladin Group',
    client6: 'Al-Futtaim (Volvo)',

    contact_title: 'Contact Us',
    contact_subtitle: 'We are here to support your next project',
    contact_address: 'Address',
    contact_phone: 'Phone',
    contact_email: 'Email',
    contact_whatsapp: 'WhatsApp',
    address_line1: 'Al Khobar – 34448 – Al Olaya',
    address_line2: 'Al Khobar, Saudi Arabia',

    footer_about_title: 'About Company',
    footer_about_text: 'A leading company in general contracting and industrial fabrication in Saudi Arabia',
    footer_contact_title: 'Contact Information',
    footer_links_title: 'Quick Links',
    footer_services_title: 'Services',
    footer_cr: 'CR: 7050607956',
    footer_copyright: '© {year} Al-Majd Al-Arabi Al-Hadith All Rights Reserved',
    footer_website: 'Website',

    login: 'Login',
    logout: 'Logout',
    profile: 'Profile',
    my_profile: 'My Profile',
    admin_panel: 'Admin Panel',
    username: 'Username',
    email_address: 'Email Address',
    password: 'Password',
    sign_in: 'Sign In',
    signing_in: 'Signing in...',
    test_account: 'Test Account',
    phone_number: 'Phone Number',
    position: 'Position',
    department: 'Department',
    member_since: 'Member Since',
    close: 'Close',
    not_provided: 'Not provided',
    not_specified: 'Not specified',
    enter_password: 'Enter your password',
    full_name: 'Full Name',
    user: 'User',
    no_position: 'No position set',

    toggle_language: 'Toggle language',
    login_failed: 'Unable to sign in',

    public_profile_title: 'Public Profile',
    public_profile_back_home: 'Back to website',
    public_profile_not_found: 'No public profile is available for this user.',
    public_profile_load_error: 'Unable to load the profile right now.',
    public_profile_whatsapp: 'WhatsApp',
    public_profile_phone: 'Phone',
    public_profile_email: 'Email',
    public_profile_share: 'Share my profile',
    public_profile_copied: 'Link copied',
    public_profile_copy_failed: 'Could not copy the link',
    public_profile_shared: 'Shared',
    public_profile_flip_hint: 'Swipe left/right to view the QR code',
    public_profile_qr_alt: 'QR code for the public profile',

    admin_public_profiles_title: 'Public Profiles',
    admin_new_user: 'New User',
    admin_logout: 'Sign Out',
    admin_default_user_aria: 'Default user',
    admin_edit_user: 'Edit User',
    admin_add_user: 'Add User',
    admin_delete: 'Delete',
    admin_field_public_code: 'Public Code (4 digits)',
    admin_public_code_hint: '4 digits (0001 to 9999). Code 0000 is reserved for the default profile.',
    admin_public_code_auto: 'Auto-generated when creating a new user',
    admin_public_code_required: 'Public code is required.',
    admin_public_code_invalid: 'Public code must be exactly 4 digits.',
    admin_public_code_reserved: 'Code 0000 is reserved for the default profile.',
    admin_field_name: 'Name',
    admin_field_position: 'Job Title',
    admin_field_phone: 'Phone',
    admin_field_whatsapp: 'WhatsApp',
    admin_field_email: 'Email',
    admin_field_image: 'Avatar URL',
    admin_account_status: 'Account Status',
    admin_status_active: 'Active',
    admin_status_inactive: 'Inactive',
    admin_default_user: 'Default Profile',
    admin_save: 'Save',
    admin_save_success: 'Saved successfully',
    admin_load_error: 'Failed to load data',
    admin_refresh_error_after_save: 'Saved, but failed to refresh the list',
    admin_refresh_error_after_delete: 'Deleted, but failed to refresh the list',
    admin_save_error: 'Failed to save',
    admin_save_error_with_reason: 'Failed to save: {message}',
    admin_delete_default_forbidden: 'The default profile cannot be deleted.',
    admin_delete_error: 'Failed to delete',
    admin_default_user_note: 'This is the default profile and cannot be deleted or edited from here. Edit it from the database only.',
    admin_qr_code: 'QR Code',
    admin_qr_alt: 'QR code',
    admin_download_png: 'Download PNG',
    admin_download_svg: 'Download SVG',
    admin_delete_modal_title: 'Are you sure you want to delete this user?',
    admin_delete_modal_user: 'User:',
    admin_delete_modal_warning: 'This action cannot be undone.',
    admin_cancel: 'Cancel',
    admin_confirm_delete: 'Yes, delete',
  },
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>('ar');

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === 'ar' ? 'en' : 'ar'));
  };

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations.ar] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, toggleLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
